apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleepy-app
  labels:
    app: sleepy-app
    environment: #{Octopus.Environment.Slug}
    project: #{Octopus.Project.Slug}
    managed-by: octopus-deploy
spec:
  replicas: #{SleepyApp.Replicas}
  selector:
    matchLabels:
      app: sleepy-app
  template:
    metadata:
      labels:
        app: sleepy-app
        environment: #{Octopus.Environment.Slug}
        project: #{Octopus.Project.Slug}
    spec:
      containers:
      - name: bash
        image: bash:5
        command: ["/usr/local/bin/bash"]
        args: ["-c", "trap : TERM INT; echo 'Sleeping...' && sleep infinity & wait"]

